### ISSUE TITLE
Send Button sending empty Messages

### ISSUE THREAD

**Issue by Sandeep03edu** [muralimanohar2002/Chatting-App#12]
User is able to sent empty text messages during chat
![Screenshot_2021-12-07-01-53-02-64_ba276dd06043669ef9378995607d185d](https://user-images.githubusercontent.com/73837113/144916992-3cc5ad93-6b38-40c3-b9dc-56dc210cf7f4.jpg)

**Comment by maityamit** [comment]
I solved this issue and pr #17
