### ISSUE TITLE
[Bug] Previous message don't appear until you text a new message

### ISSUE THREAD

**Issue by muralimanohar2002** [muralimanohar2002/Chatting-App#2]
## Summary

Once you open the chat section for a particular user, the previous conversation with that person aren't shown up until you text him another message. 

## How to reproduce the bug
- Text some random text to a person. 
- Get back to the main screen.
- Again open the inbox for that particular person whom you have texted.
- Voila!!! Chats disappeared.

**Comment by adarshares** [comment]
I would like to work for this issue.

**Comment by muralimanohar2002** [comment]
> @muralimanohar2002 I would like to work for this issue.

Yes you can work on this issue. Feel free to ask doubts.

**Comment by Sandeep03edu** [comment]
I am working on this issue

**Comment by Sandeep03edu** [comment]
Solved issue and created a pull request - Solved Issue#2 : [Bug] Previous message don't appear until you text a new message
