### ISSUE TITLE
[FEATURE] Displaying recent message delivery time at chat section page.

### ISSUE THREAD

**Issue by muralimanohar2002** [muralimanohar2002/Chatting-App#5]
## Screenshot

![time_chatapp](https://user-images.githubusercontent.com/61517067/144752668-9f567235-fb6f-40cc-a407-d77fe983cab7.jpeg)

## Summary

- While going through various layout files, one can find the item layout for the recycler view of user displayed on the very first screen on starting the app. A text view is already added for the time section but the logic to display time is needed to be implemented.

**Comment by Sandeep03edu** [comment]
I am working on it

**Comment by Sandeep03edu** [comment]
Added new feature and created a new Pull Request for the same "Solved issue#5"
